### ISSUE TITLE
How to set the encoding of Ably messages?

### ISSUE THREAD

**Issue by NikitaKemarskiyLeia** [ably/kafka-connect-ably#109]
Hello! I use Ably-Kafka Connector, and I want to apply GraphQL Subscriptions schema to my deployment using https://github.com/ably-labs/graphql-ably-pubsub. So I want to do the following: event published to Kafka topic -> message added to Ably channel by Ably-Kafka Connector -> message consumed by Node.js backend using graphql-ably-pubsub library -> message published to frontend using GraphQL Subscriptions.

I've almost set everything up, but I face a problem with serialization. It seems like messages are consumed from Ably in different ways when I use graphql-ably-pubsub to publish to Ably VS when I use Kafka Connector.

Below you can see two messages: the upper one is published via Kafka, and the lower is published by graphql-ably-pubsub. As I can see, the only difference is the "encoding" field. My hypothesis is that graphql-ably-pubsub isn't compatible with the message from Kafka connector because of this field. How can I set it up for Ably Kafka Connector?

<img width="1202" alt="Screenshot 2023-03-10 at 16 46 33" src="https://user-images.githubusercontent.com/93923641/224361231-d17bbbce-0ec2-4a1e-9843-3e0f45a6ff62.png">

Also maybe there is another cause of the problem? I would be glad to hear your opinion.

**Comment by NikitaKemarskiyLeia** [comment]
Error in Apollo Client looks like this (because it can't recognize message data correctly):
<img width="369" alt="Screenshot 2023-03-13 at 11 59 04" src="https://user-images.githubusercontent.com/93923641/224668703-957a4d84-235c-46c0-a3c3-99c7df0f034c.png">

**Comment by NikitaKemarskiyLeia** [comment]
So to fix the issue I need an ability to specify Message.encoding request attribute for publishing messages to the Ably channel: https://ably.com/docs/api/rest-api#publish

**Comment by ikbalkaya** [comment]
@NikitaKemarskiyLeia In Ably Kafka connector, when publishing messages without a schema the 'encoding' field is not set. It's only set to `json` when there is a schema on Kafka record. 

My understanding is that you want to be able to set `encoding` on connector to consume messages compatibly in other sides. Can you confirm that this is the case?  I have not used graphql's pub-sub but would it be easier to use the same encoding rules as in Kafka connector? For example by not specifying encoding. 

And also will you be able to provide an example Kafka record and what message you expect to see on subscriber side so I can offer further help.

**Comment by NikitaKemarskiyLeia** [comment]
@ikbalkaya Yes, you are right. Probably it will work for us, I've just found it in the source code: https://github.com/ably/kafka-connect-ably/blob/04a0143b5ed1376dcfcaf4818bc7ee148f4ccbdb/src/main/java/com/ably/kafka/connect/mapping/DefaultMessageSinkMapping.java#L57.

We will try to add a schema for the topic, if it won't work I'll try to change the subscriber side. Thank you. Let's please keep this issue open until I resolve the issue.

**Comment by ttypic** [comment]
@NikitaKemarskiyLeia Hello! Have you resolved the issue? Can we close it now? By the way in the last release we added support of `encoding` through special Kafka Header, so you can make it work even without schema
