### ISSUE TITLE
Submit records using Batch API

### ISSUE THREAD

**Issue by jaley** [ably/kafka-connect-ably#124]
Currently, the Ably connector submits messages to Ably using a single Realtime connection. This limits throughput and the maximum number of channels that can be used from a single `ChannelSinkTask`. Given that we support dynamic mapping of `SinkRecord` to Ably channels, it can be hard for users to control the number of distinct outgoing channels from a single sink task.

Moving to the Batch REST API will improve this, particularly with parallel submissions of batches, at the cost of message ordering. We propose making parallelism configurable, so that users can select to either have very high throughput at the cost of ordering, or maintain ordering for more limited throughput per channel sink task.

**Comment by jaley** [comment]
Note this is implemented in #116

**Comment by stmoreau** [comment]
Implemented in https://github.com/ably/kafka-connect-ably/pull/125
