### ISSUE TITLE
Missing converters for JsonSchema, Avro etc

### ISSUE THREAD

**Issue by mclark-ably** [ably/kafka-connect-ably#163]
Feature request to add the following to the MSK which need to be added manually if required

https://github.com/aws-samples/msk-config-providers/releases/tag/r0.2.0
https://www.confluent.io/hub/confluentinc/kafka-connect-json-schema-converter

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4626) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment]
I do not believe this is an issue from what I have seen. Any converter can be easily specified in the config, see https://github.com/ably/kafka-connect-ably?tab=readme-ov-file#confluent-cloud-custom-connector for example.

@ttypic do you agree with above?

If so, would this issue be resolved with just improvements in the docs?

**Comment by ttypic** [comment]
@mattheworiordan not sure I understand what this issue is about

**Comment by mattheworiordan** [comment]
@mclark-ably I am closing this issue as I don't believe this is in fact an issue, and is instead a misunderstanding in how to use native convertors. Would you mind reaching out to whoever mentioned this isuse to see if they can clarify the problem, and we'll happily reopen this ticket.
