### ISSUE TITLE
Issue when installing the connector

### ISSUE THREAD

**Issue by ginotoro** [ably/kafka-connect-ably#18]
Describe the problem you have found:

As part of the Ably Kafka Sink Connector verification process, I started working on verifying the connector resources. While building the connector, I am seeing the following issue. Tried different permutations like modifying settings.xml, pom.xml  but without any success and eventually found this URL https://dl.bintray.com/palantir/releases/ , its seems they winded up business and now running under  a different name JFrog. Could you please suggest any workarounds for the same or share the approach your team following for building the connector.

![image](https://user-images.githubusercontent.com/73481596/127483638-75cfc876-45ef-4626-b964-17e9d7bdd603.png)

How to reproduce:

Setup:
OS : Windows 10
JDK : Both 1.8 and 11
Apache Maven 3.8.1
Run 'mvn clean package'

┆Issue is synchronized with this [Jiraserver Task](https://ably.atlassian.net/browse/ING-16) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Snippet of output from Maven 3.8.1 using `mvn help:effective-pom` per [this answer](https://stackoverflow.com/a/2877453):

```
  <repositories>
    <repository>
      <id>confluent</id>
      <url>http://packages.confluent.io/maven/</url>
    </repository>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </pluginRepository>
  </pluginRepositories>
```

Which makes me wonder / worry whether this is outside of our control... but need to dig deeper.

**Comment by lmars** [comment]
This was fixed in https://github.com/ably/kafka-connect-ably/pull/19.
