### ISSUE TITLE
Consider rewriting the project in Kotlin

### ISSUE THREAD

**Issue by KacperKluka** [ably/kafka-connect-ably#21]
Kotlin is a modern language that's fully compatible with Java. It should be possible to rewrite the project in Kotlin and it will be much cleaner. There are automatic tools for converting Java to Kotlin but they have flaws so someone with Kotlin knowledge would have to look at the code and fix it if needed.

However, this might not be a popular choice in this domain, as almost all projects use Java.

**Comment by ikbalkaya** [comment]
Good idea :) 
> However, this might not be a popular choice in this domain, as almost all projects use Java.

I also think that's the case.  Kotlin might be a bit unexpected for people navigating our source code. So I'm going to close this.
