### ISSUE TITLE
Missing maintainers file

### ISSUE THREAD

**Issue by QuintinWillison** [ably/kafka-connect-ably#29]
We've been conforming to have one of these in every repository, primarily for internal purposes ('which team?').

e.g. per [this one](https://github.com/ably/ably-java/blob/main/MAINTAINERS.md).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/REC-43) by [Unito](https://www.unito.io)

**Comment by lmars** [comment]
> which team?

This falls under the Integrations team, although it hasn't been staffed yet.

**Comment by AndyNicks** [comment]
https://github.com/ably/kafka-connect-ably/commit/05d9bb542c65111fcf11e699d7d954e4a402f88f
