### ISSUE TITLE
Proxy settings are not used in the code

### ISSUE THREAD

**Issue by vykulakov** [ably/kafka-connect-ably#35]
Ably Kafka connector version: 1.0.2

I tried to find the root case of my issues with the Ably Kafka connector and found out that the proxy config is not used in the client options object:

```
    opts.recover = getString(CLIENT_RECOVER);
    if (getBoolean(CLIENT_PROXY)) {
      ProxyOptions proxyOpts = new ProxyOptions();
      proxyOpts.host = getString(CLIENT_PROXY_HOST);
      proxyOpts.port = getInt(CLIENT_PROXY_PORT);
      proxyOpts.username = getString(CLIENT_PROXY_USERNAME);
      proxyOpts.password = getPassword(CLIENT_PROXY_PASSWORD).value();
      proxyOpts.nonProxyHosts = getList(CLIENT_PROXY_NON_PROXY_HOSTS).toArray(new String[0]);
      proxyOpts.prefAuthType = HttpAuth.Type.valueOf(getString(CLIENT_PROXY_PREF_AUTH_TYPE));
    }
    opts.environment = getString(CLIENT_ENVIRONMENT);
```

I expect a line like

```
opts.proxy = proxyOpts;
```

at the end of the `if` block above but don't see it, unfortunately.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1951) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Thanks for reporting and sorry for the late response. Your analysis looks correct, we just need to validate that the underlying Java client library supports these options.

**Comment by AndyTWF** [comment]
This issue has been resolved in Version 3 of the connector :)
