### ISSUE TITLE
Connector cannot JSonify Date object

### ISSUE THREAD

**Issue by ikbalkaya** [ably/kafka-connect-ably#97]
Raised by our customer, it looks like when Avro schema with 

```
"type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
```
Is provided and a record like 

`{"timeAt":1671413240210}`

is given ably-kafka-connector  raises an exception. An excerpt from top of stact trace

`by: java.lang.ClassCastException: class java.util.Date cannot be cast to class java.lang.Long (java.util.Date and java.lang.Long are in module java.base of loader 'bootstrap')\n\tat org.apache.kafka.connect.data.Struct.getInt64(Struct.java:130)\n\tat com.ably.kafka.connect.utils.StructToJsonConverter.structJsonMap(StructToJsonConverter.java:71)\n\tat com.ably.kafka.connect.utils.StructToJsonConverter.toJsonString(StructToJsonConverter.java:27)\n\tat `

So this issue seems to be a bug with **Kafka Connect Data** framework  as their internal framework cannot properly create a data type given by schema. In fact `Date` type isn't even defined in Kafka connect framework. Or possibly a compatibility version issue... Need to investigate.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/REC-74) by [Unito](https://www.unito.io)

**Comment by alaksmana** [comment]
https://github.com/ably/kafka-connect-ably/blob/main/src/main/java/com/ably/kafka/connect/utils/StructToJsonConverter.java

Since we use Avro, we would need Logical Types conversion as well on top of the Primitives. https://avro.apache.org/docs/1.8.2/spec.html 

Especially: Decimal, Date, Timestamp (millis)
